# -*- coding: utf-8 -*-
"""Pegasus model .ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Olca48NEYHfUky7LqZrROtDegOsyHA7j

# 0. Install dependencies
"""

# Install PyTorch
!pip install torch==1.11.0+cu111 torchvision==0.9.2+cu111 torchaudio===0.8.2 -f https://download.pytorch.org/whl/lts/1.8/torch_lts.html

# Install transformers
!pip install transformers

"""# 1. Import and Load Model"""

from transformers import AutoTokenizer, AutoModelForSeq2SeqLM

tokenizer = AutoTokenizer.from_pretrained("google/pegasus-xsum")

model = AutoModelForSeq2SeqLM.from_pretrained("google/pegasus-xsum")

# Importing dependencies from transformers
from transformers import PegasusForConditionalGeneration, PegasusTokenizer

# Commented out IPython magic to ensure Python compatibility.
# %pip install sentencepiece

# Load model 
model = PegasusForConditionalGeneration.from_pretrained("google/pegasus-xsum")

"""# 2. Perform Abstractive Summarization"""

text = """The 34-year-old has been absent from the club since a training-ground row after the 5-1 Scottish Premiership loss at Celtic on 10 September.
Alongside agent Eddy Jennings, he attended a meeting with club officials last week. Barton, who joined from Burnley in May, has repeatedly
said he wants to return and fight for his Rangers place. ”Joey Barton has been told he will return to full-time training following the conclusion
of a disciplinary procedure,” read a statement on Rangers’ website. ”The Auchenhowie [training base] management team will inform the player
of appropriate training arrangements to which he must adhere for as long as he remains a Rangers player. ”Neither the club, nor the player, will
comment further.” Barton is also facing Scottish FA charges for breaching betting rules. He was charged with placing 44 bets on games between 1
July and 15 September. The former Manchester City, Newcastle United and QPR player, who has one England cap, left Burnley under freedom of
contract at the end of last season, signing a two-year contract at Ibrox. He has made eight appearances for Mark Warburton’s side, who are second in
the Premiership. Barton was not available for comment but said earlier on Wednesday on Twitter that it was ”a lovely day for a Iceman Hof session
and a run!” in reference to Dutch ice bath training guru Wim Hof. BBC Scotland’s Richard Wilson The fact that Joey Barton is returning to full-time
training does not necessarily mean the resumption of his Rangers career. Under Fifa rules, a player under contract at a club must be provided with
training facilities. The fact that the player was suspended reflects the view of the management team about the serious nature of a training-ground row
in September. Any return to the first-team squad would need to be """

# Create tokens - number representation of our text
tokens = tokenizer(text, truncation=True, padding="longest", return_tensors="pt")

# Input tokens
tokens

# Summarize 
summary = model.generate(**tokens)

# Output summary tokens
summary[0]

# Decode summary
tokenizer.decode(summary[0])

!pip install rouge

from rouge import Rouge

gold = "Rangers say midfielder Joey Barton ”will return to full-time training” following a club-imposed suspension."

model_summary = " Rangers midfielder Joey Barton has been told to return to full-time training."

rouge = Rouge()
scores = rouge.get_scores(gold, model_summary)
print (scores)